---
# tasks file for php
- name: "Adicionando repositório"
  yum:
     name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     state: latest
        
- name: "Habilitante repositório"
  command: yum-config-manager --enable remi-php73

- name: Instalando pacotes PHP
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - php
      - php-fpm
      - php-common
      - php-mysql
      - php-gd
      - php-xml
      - php-mbstring
      - php-mcrypt
      - php-opcache
      - php-pecl-apcu
      - php-cli
      - php-pear
      - php-pdo
      - php-mysqlnd
      - php-pgsql 
    state: present
    update_cache: yes

- name: Copiar arquivo de www.conf do blog para a pasta do php-fpm
  template:
        src: www.conf.j2
        dest: /etc/php-fpm.d/www.conf

- name: start php-fpm
  command: systemctl start php-fpm

- name: enable php-fpm
  command: systemctl enable php-fpm

- name: Restart Daemon
  command: systemctl daemon-reload