---

- name: Instalar MariaDB
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - mariadb
      - mariadb-server
      - python-pip 
    state: present
    update_cache: yes

- name: "Verificando se o  pymysql esta presente"
  pip:
    name: PyMySQL
    state: present

- name: start mariadb
  command: systemctl start mariadb

- name: enable mariadb
  command: systemctl enable mariadb

- name: "Criar banco WordPress"
  mysql_db:
    name: wordpress
    state: present

- name: "Criar usuário e senha no banco para o WordPress"
  mysql_user:
    name: wordpress
    password: wordpress
    priv: wordpress.*:ALL
    host: "localhost"
    state: present
  notify: restart mariadb