---
# tasks file for nginx
- name: Install Nginx
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - nginx
    state: present
    update_cache: yes

- name: start nginx
  command: systemctl start nginx

- name: enable nginx
  command: systemctl enable nginx

- name: Copiar arquivo de config do blog para a pasta do Nginx/conf.d
  template:
        src: blog-config.j2
        dest: /etc/nginx/conf.d/blog-config.conf
  notify: restart nginx