---

- name: Restart Daemon
  command: systemctl daemon-reload
  
- name: start php-fpm
  service: 
    name: php-fpm 
    state: started
    enabled: yes

- name: restart php-fpm
  service: 
    name: php-fpm 
    state: restarted
    enabled: yes