---

- name: Atualizando Centos 7
  yum:
    name: '*'
    state: latest
    

- name: Instalando pacotes Padrões
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - epel-release
      - net-tools
      - wget
      - curl
      - vim
      - unzip
    state: latest
    update_cache: yes

#- name: Adicionando grupo nginx
#  group: 
#    name: nginx

#- name: Adicionando usuário nginx
#  user: 
#    name: nginx 
#    group: nginx